### ISSUE TITLE
What should my Git config be?

### ISSUE THREAD

**Issue by digisavvy** [Chassis/Chassis#165]
This is more of a question. But when using Git to push with WP Engine or Pantheon, what am I adding to git source? I'm confused on how to set up version control for my projects. I checked the docs and I also checked existing issues and didn't see anything referencing that.

**Comment by BronsonQuick** [comment]
Hey @digisavvy! Good question :smile: This isn't really a Chassis related question. It's more of a workflow question but that being said, I'm happy to answer this for you anyways.

I track all my themes and plugins in Git and ignore the WordPress `uploads` folder. I think it's best to track any code other than WordPress core in your Git repository.

**Comment by digisavvy** [comment]
Hi @BronsonQuick, thanks for such a quick reply. I guess my question is how to version things correctly. So right now I just have my content folder in version control. I've added my remote repo and when I push to my remote, the file son content appear in the root directory (not under the wp-content folder), so there's some configuration there that I'm not doing right. Am I explaining that well?

**Comment by BronsonQuick** [comment]
Hi @digisavvy! Yeah that makes sense :+1:

You've got two options you can do to resolve this. The first one is to make the folder structure on the server match Chassis' folder structure or you could use http://deploybot.com/ and have your local `content` folder pushed into the `wp-content` folder on your remote server. I normally use http://deploybot.com/ on WP Engine and Pantheon. I know they both have Git integration but because I don't keep WordPress core under version control http://deploybot.com/ is a good solution. I hope that helps :smile:

**Comment by digisavvy** [comment]
That helps. I'm using a push to git setup with Pantheon. But this question would also apply to WP Engine.  I'll dig around some more. =)

Thanks.
