### ISSUE TITLE
/extensions/ page path does not work

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Chassis#178]
We happen to have a page on our site that is `siteurl.com/extensions/`. Turns out Chassis throws a `403 Forbidden` when attempting to load this page. I assume this is because of the conflict with the `extensions` folder?

**Comment by BronsonQuick** [comment]
Hrey @ericnicolaas, yeah that's correct. It's because of the extensions. You might be able to work around this by commenting out or modifying:

https://github.com/Chassis/Chassis/blob/master/puppet/modules/chassis/manifests/wp.pp#L56 and
https://github.com/Chassis/Chassis/blob/master/puppet/modules/chassis/templates/local-config-extensions.php.erb then running `vagrant provision`.

As this is a pretty small edge case you've hit I'm going to close this out. If someone else hits this as well and reopens the issue in the future we might try and figure a workaround. I hope that at least helps.

**Comment by rmccue** [comment]
If you're not using extensions, deleting the directory should be enough to cause it to route correctly to WP.
