### ISSUE TITLE
Support for pulling themes and plugins from a repo

### ISSUE THREAD

**Issue by harleyoliver** [Chassis/Chassis#239]
If possible, running theme and plugin installs set in config.yaml that are sourced from a git repository

**Comment by tpkemme** [comment]
This is the biggest thing I've found chassis is lacking.. it would be really nice if i could create a chassis box for local development that would automatically pull my themes/plugins being developed from the config.yaml.  That way i could create a git repo/gist with only the config.yaml file for recreating my dev environment..

**Comment by shadyvb** [comment]
Chassis uses wp-cli under the hood to install plugins, which in turn supports passing URLs to zip file, see example in [wp-cli documentation](https://developer.wordpress.org/cli/commands/plugin/install/). So using something like `https://github.com/envato/wp-envato-market/archive/master.zip` should probably work. Themes though do not have the same functionality ( [limitation](https://github.com/rmccue/puppet-wp/blob/master/manifests/theme.pp) of the puppet library used by Chassis, PRs are welcome! ).

This does not support GitHub Repo URLs though, nor zip links from private GitHub repos ( because, auth ), not sure if wp-cli has plans to support that any time soon.

However, the usual approach taken in such scenarios would be to submodule whatever plugins/themes you need in your repo. So you'd have better control on what versions/branches are used for your dependencies.
