### ISSUE TITLE
Invalid parameter php_package

### ISSUE THREAD

**Issue by noplanman** [Chassis/Chassis#291]
`Error: Invalid parameter php_package on Class[Wp] at /vagrant/puppet/modules/chassis/manifests/php.pp:90`

I've been having this error pop up when provisioning.
After destroying and recreating the box with a fresh installation I still get it.

Is there something in my configs that might be causing this?

Edit:
After just removing that whole `class` block, everything works fine. What does it actually do?

**Comment by rmccue** [comment]
We updated the `puppet/modules/wp` submodule, which will cause this error. Have you tried updating submodules (`git submodule update --init --recursive`)?

That class is responsible for installing wp-cli onto the server; on updates, it won't do anything, since wp-cli is already installed, which is why you're not seeing any difference here.

**Comment by noplanman** [comment]
@rmccue Thanks for your reply.

Looks like there was some update issue for the wp submodule and the `params.pp` didn't have the `$php_package =` section in it.

After a revert and fresh update all is good now, gracias!
