### ISSUE TITLE
Add a new ppa for Php 5.5

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#295]
Php 5.5 was dropped in the ppa we are using: https://twitter.com/debsuryorg/status/808284372356825088 we should find an alternate ppa to maintain Php 5.5 support.

**Comment by BronsonQuick** [comment]
I'm closing this as it looks like it's not going to be supported.

**Comment by ZerooCool** [comment]
PPA -> PHP 5.2 <-> PHP 7.4
https://wiki.visionduweb.fr/index.php?title=Installer_PHP#Installer_diff.C3.A9rentes_versions_de_PHP_avec_un_PPA

**Comment by BronsonQuick** [comment]
@ZerooCool Amazing! Thanks so much for that. I'll try and add back PHP 5.2 -> PHP 5.5. Thanks so much!

**Comment by BronsonQuick** [comment]
I've just been having a play around with this and there aren't `bionic` releases for those older PHP versions so I think what I'll need to do is make another `xenial` base based on the `2.2` release and ship that so we can use those older PHP versions.

**Comment by BronsonQuick** [comment]
I've changed my mind on this because I'd need to maintain an older version of WordPress core as well because the most recent version throws this error on 5.2 -> 5.5.
>Your server is running PHP version 5.3.29-Ubuntu/16.04-SergeyD/14.4 but WordPress 5.3 requires at least 5.6.20.

**Comment by ZerooCool** [comment]
Indeed, I am not aware of the problems related to the use of PPAs that I shared with you. I did it because, in my search for PPA, I came across this Github issue, and, I thought it would be interesting to complete it, both for you, but also for other people who would look for a working list of PPAs (With a link that works, unlike other tutorials that share links that no longer work.)

For their integration, it's up to you to see what would suit you best, I absolutely do not know how to position myself on this project that I discovered yesterday.

Otherwise, as mentioned on the Ubuntu forum post where I also shared this list, there are of course other possibilities:
- Compile or even the PHP version from sources.
- Use phpbrew which seems very interesting but which I have not tested.

My contribution on the Ubuntu forum : https://forum.ubuntu-fr.org/viewtopic.php?pid=22196586
