### ISSUE TITLE
Chassis multisite permalink issue

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#336]
So when creating a multisite the default `permalink` for the default site uses `/wp/` in the URL i.e: http://vip.local/wp/2017/03/01/hello-world/ however if you remove http://vip.local/2017/03/01/hello-world/ from said URL it also works. I'm assuming this is an issue with Chassis and how it does the permalinks. 

Please see https://github.com/stuartshields/chassis-vip/issues/12 for further information.

**Comment by fklein-lu** [comment]
This could be of help: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf#L40

**Comment by johnbillion** [comment]
Turns out Chassis already has this (or somthing very similar) but it's commented out: https://github.com/Chassis/Chassis/blob/7daa986d5a37b11451ded56c8e738fa45a9c21cc/puppet/modules/chassis/templates/multisite.nginx.conf.erb#L21-L28

I'm gonna play with it and see what breaks.

**Comment by rmccue** [comment]
Treating this as critical, will try and fix ASAP.

**Comment by rmccue** [comment]
This is very strange, but happens upon install. The command that's run to install:

```
wp core multisite-install --subdomains --url='http://vagrant.local/' --title='WordPress Site' --admin_email='admin@example.com' --admin_name='admin' --admin_password='password'
```

This sets up wp_blogs correctly, with `path=/`. However, `siteurl` and `home` for the site are set incorrectly. This is because `WP_SITEURL` is set. For some reason, WP uses `WP_SITEURL`, but **not** `WP_HOME` when converting. This seems like a core bug.

In any case, with the newer nginx rules we have, we don't need `/wp` in the URL, so we can remove it from the `WP_SITEURL` constant.

**Comment by rmccue** [comment]
> In any case, with the newer nginx rules we have, we don't need /wp in the URL, so we can remove it from the WP_SITEURL constant.

^ this is only for multisite. However, not setting the constant during `WP_INSTALLING` fixes for both.
