### ISSUE TITLE
Change `puppet-lint` to use tabs

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#354]
Anywhere that calls `puppet-lint` for builds across our repos should use tabs, not spaces.

**Comment by ntwb** [comment]
I switched to spaces because of this: 
> https://docs.puppet.com/puppet/latest/style_guide.html#spacing-indentation-and-whitespace
> Module manifests: 
> > Must use two-space soft tabs
> > Must not use literal tab characters,

I didn't research much further than that, I'm assuming they have that recommendation as some parsers of the manifests don't play well with tabs, similar to YAML.

See also http://puppet-lint.com/checks/2sp_soft_tabs/ & http://puppet-lint.com/checks/hard_tabs/

Happy to switch back to tabs over spaces and update all the things 😄

**Comment by BronsonQuick** [comment]
I think the best way to tackle this would be to write our own puppet-lint plugin for to check for tabs and disable both the checks @ntwb mentioned.

I'd also like us to add in the `trailing_newlines` plugin in our checks as well

**Comment by ntwb** [comment]
Sounds good to me 👍 

I just had a quick search on GitHub if any such ''tabs'' puppet plugin already exists, nope

I did see this one that we might want to consider:
• https://github.com/voxpupuli/puppet-lint-trailing_comma-check
