### ISSUE TITLE
Document how to use Chassis for WordPress Core development

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#378]
We haven't documented this yet and I've had a few people ask me about this.

I posted a bit of a note about it in our WordPress Australia Slack a while back but it needs to be fleshed out properly. I'll log that here.

Create two folders:
`wpcore` - Contains a clone of WordPress develop
`wpcore-box` - Contains a clone of Chassis

Edit the paths in your yaml file
```
paths:
	# Base directory for reference. Relative to the Chassis directory.
	base: .

	# Where WordPress lives. Relative to the base directory.
	wp: ../wpcore/src

	# Content directory. Relative to the base directory.
	content: content
```
Edit the synced folders in your yaml file:
```
synced_folders:
	logs/nginx: /var/log/nginx
	logs/php: /var/log/php
	"../wpcore": /vagrant/extensions/tester/wpdevel
```
Copy up `wp-config-sample.php` to `../wpcore/src`
Run `vagrant provision`

**Comment by ntwb** [comment]
The following two documentation sections should also be tweaked/merged at the same time as the key `wpdir` has been deprecated in favour of the `paths` key: 

> http://docs.chassis.io/en/latest/config/#wordpress-directory
> http://docs.chassis.io/en/latest/config/#paths

**Comment by ericnicolaas** [comment]
@BronsonQuick I've been trying to get this set up. Using a fresh copy of Chassis and a fresh download of WP develop.

Provisioning ends with this: 

<img width="851" alt="screenshot 2017-06-15 14 24 33" src="https://user-images.githubusercontent.com/676582/27165918-5f1179e6-51d6-11e7-9b1b-393984c45732.png">

So the issue is that the `wp-config.php` file is missing. I tried adding one with the Chassis box db user, name and password from Chassis, which gets the site installed but means that all of the other config from Chassis' regular `wp-config.php` are missing, like the definition of `WP_CONTENT_DIR` and `WP_SITEURL`.

I'm guessing I'm missing something simple. Any ideas?

**Comment by BronsonQuick** [comment]
Adding a link to a doc @rmccue just typed up so I don't forget the URL: https://gist.github.com/rmccue/8b6c03db879cf785b433e65c860806f3

**Comment by BronsonQuick** [comment]
Fixed via https://github.com/Chassis/Chassis/pull/430
