### ISSUE TITLE
Clarification around dependencies that break

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#384]
I'm not super hot on vagrant and puppet, so I'd like some clarification on how a few things work.

As part of the project onboarding for a client project, Chassis is used to set up a local development environment (with a custom `config.yaml` in the `content` directory). This means Chassis is an important part of the project setup and development workflow.

At some point (possibly within the last few days) the provisioning for this stopped working due to a broken dependency.

    Couldn't find any package by regex 'php7.0-xml'

This caused a cascade of errors that prevented the box from provisioning.

Where within Chassis are these sort of dependencies defined? Why would this suddenly stop working and prevent the box from provisioning? Is this outside of our control or should Chassis instead pin more of its dependencies to specific versions in order to prevent this sort of breakage?

**Comment by rmccue** [comment]
Chassis has one key dependency: `ppa:ondrej/php` This supplies the Ubuntu PHP packages for anything not included in the official repository (that is, anything that's not 5.3).

Unfortunately, the maintainer [deleted all the packages](https://twitter.com/debsuryorg/status/869185204908326912). This happened to us before, when `ppa:ondrej/php-oldstable` was deleted, and we lost 5.4 and 5.5. There's nothing we can do about this, because they're straight up deleted from the canonical (heh) source. (We could potentially mirror them, but that's tough.)

None of our other dependencies have ever broken. All the git submodules are pinned, and our other packages are official packages from the fully-supported Canonical repo.

**Comment by johnbillion** [comment]
Thanks for the info 👍
