### ISSUE TITLE
Start tagging releases?

### ISSUE THREAD

**Issue by joehoyle** [Chassis/Chassis#393]
Given that the master branch seems pretty broken for me right now, maybe tagging known stable releases would be a good idea so we can always have something to install even when master is borked?

**Comment by rmccue** [comment]
The problem with tagging releases is that it wouldn't necessarily fix any of these issues, because we're tied to a tonne of external dependencies. (Don't even get me started on `ppa:ondrej/php`)

#392 for example seems like an underlying change to the nginx package on Ubuntu's side, which tags wouldn't help with.

We could potentially pin every package version, but this runs into other problems when minor versions are deleted from the external repositories (this mainly occurs with PPAs rather than universe packages though).

With that said, we should start tagging to allow us to version base boxes for #390.

**Comment by joehoyle** [comment]
That's true, however it would be good to have even releases of this repo, for example the master branch is pretty broken right now; with 16.04 and #391

**Comment by LewisCraik** [comment]
This is something that I was also thinking would be useful.

**Comment by BronsonQuick** [comment]
>That's true, however it would be good to have even releases of this repo, for example the master branch is pretty broken right now; with 16.04 and #391 

VMWare is the exception at the moment and I'm only aware of a few people in Human Made who are still using VMWare at the moment. Everyone in community using Chassis is using VirtualBox and they rarely have issues. I do intend to circle back with VMWare testing in a few weeks though.

I've just tagged master as `2.0` https://github.com/Chassis/Chassis/releases/tag/2.0 and I'll have a chat to Ryan about how he'd like to version things going forward.
