### ISSUE TITLE
Why not have `wp` as a submodule?

### ISSUE THREAD

**Issue by joehoyle** [Chassis/Chassis#396]
Currently if you already have a full WP install and are using Chassis in such a configuration, WordPress must be fully downloaded by cloning this repo. Is there any reason why wp is not a submodule?

**Comment by BronsonQuick** [comment]
We have `wp` as a subtree so it's smaller in file size when you download the repo and it eliminates potential issues people seem to have with submodules. We could've done a submodule with `--depth=1`but by using a subtree it takes the hassle out of it.

We could potentially remove `wp` from this repo and have a config flag that pulls it in but I'll let @rmccue weigh in about whether or not that's a good idea or not!

**Comment by rmccue** [comment]
Submodules require you to pull the entire history of WordPress ever, which is a huge clone, so that's why we picked subtree instead.

Being able to BYO your own copy of WP is much newer, and we never changed it. Doing so now would break compatibility, and it's not really a huge issue mostly. (We can never make the repo smaller, so it wouldn't improve the speed of a clone.)

In any case, using submodules wouldn't achieve anything, because we force them to be up-to-date.
