### ISSUE TITLE
PHP notice WP_HOME constant not defined in local config

### ISSUE THREAD

**Issue by pdewouters** [Chassis/Chassis#487]
1. What operating system do you use?
Mac OS

2. What version of Vagrant are you running?
2.0.1
3. Are you using VirtualBox or VMWare and which version are you using?
virtualbox
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
no
5. Do you have any Chassis extensions installed? If so, what are they?
xdebug

`PHP Notice:  Use of undefined constant WP_HOME - assumed 'WP_HOME' in /vagrant/local-config.php on line 16`

**Comment by BronsonQuick** [comment]
I'm guessing you might've copied `local-config-sample.php` to `local-config.php` and made some modifications. If that's the case can you please attach the contents of your `local-config.php` so I can replicate this. I don't think this is an issue in Chassis it's just a configuration issue. Thanks!

**Comment by pdewouters** [comment]
```
<?php
// Note: Database constants are set in the automatically-generated
// local-config-db.php. Change these via your config.local.yaml instead.

// Loopback connections can suck, disable if you don't need cron
define( 'DISABLE_WP_CRON', true );

// You'll probably want Automatic Updates disabled during development
define( 'AUTOMATIC_UPDATER_DISABLED', true );

// You'll probably want debug logging during development
define( 'WP_DEBUG_LOG', true );
define('WP_DEBUG_DISPLAY', false);
define( 'WP_CACHE', false );
define( 'WPMU_PLUGIN_DIR', dirname( __FILE__ ) . '/content/content/plugins-mu' );
define( 'WPMU_PLUGIN_URL', WP_HOME . 'content/content/plugins-mu' );
```

**Comment by BronsonQuick** [comment]
Thanks for that @pdewouters! I'm still not able to replicate it yet ☹️

The `content/content/` rather than just `content/` seems a little strange but I know Chassis is new to you so I think we might need to improve our docs.

`plugins-mu` instead of `mu-plugins` sounds like you're trying to use Chassis with a HM setup with maybe something like `hm-base` perhaps? If that's the case then let me know about your setup and what you're trying to achieve and I should be able to help you out with this! Thank you Sir!

**Comment by pdewouters** [comment]
yeah sorry for being vague. it is indeed for the HM network. I think Dan and Rob have been working on something related so I'll check that out.
