### ISSUE TITLE
If hostsupdater is present, use it.

### ISSUE THREAD

**Issue by kadamwhite** [Chassis/Chassis#793]
1. What operating system do you use? **Ubuntu 19.10, Ubuntu 20.04**
2. What version of Vagrant are you running? **2.2.7**
3. Are you using VirtualBox? **6.1**

The logic in the Vagrantfile is convoluted, and requires multiple flags to be set in the configuration file before `hostsupdater` will take effect -- and even if `hostsupdater` is true, the conditional still may not get hit. I would like to propose that, if the hostsupdater plugin is installed, we use it as-is, without all these escape hatches. It has been _infuriating_ to get Chassis working these past few days and the inconsistency around when the hostsupdater plugin would get skipped was no small part of my frustration. :pray: thanks for all the work on the Vagrantfile, but I believe simplifying the logic would go a long way.

**Comment by BronsonQuick** [comment]
Yeah I'm happy to circle back to update the logic here. I should've probably added more comments around the logic as it's there for back compat. I definitely understand and feel your frustrations but please not that inherently this has all happened due to a bug in Vagrant and it's actually not Chassis fault. I'm really hoping they do a Vagrant release soon. The last one was in January 😢. I've seen this bug affect quite a few other projects too and people have been having to document manual hacks in their READMEs. I think that's something we're going to have to do too.

The even more frustrating part is that it's not a consistent error so some older Chassis sites will still work but some won't so there's some kinda configuration difference or setup issue that triggers the bug. It's very annoying!
